variables:
  HUB_REGISTRY: "https://index.docker.io/v1/"
  HUB_REGISTRY_IMAGE: "ctcampbellcom/veracode-tools"
  # https://veracode.slack.com/archives/C1XSH0ZNK/p1563894130003800?thread_ts=1563884976.002300&cid=C1XSH0ZNK
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  only:
    refs:
      - schedules
    changes:
      - Dockerfile
  before_script:
    - docker login -u $HUB_REGISTRY_USER -p "$HUB_REGISTRY_PASSWORD" $HUB_REGISTRY
  script:
    - docker build --no-cache --pull -t $HUB_REGISTRY_IMAGE .
    - docker push "$HUB_REGISTRY_IMAGE"
