variables:
  HUB_REGISTRY: "https://index.docker.io/v1/"
  HUB_REGISTRY_IMAGE: "ctcampbellcom/veracode-tools"

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  only:
    - schedules
    changes:
      - Dockerfile
  before_script:
    - docker login -u $HUB_REGISTRY_USER -p "$HUB_REGISTRY_PASSWORD" $HUB_REGISTRY
  script:
    - docker build --no-cache --pull -t $HUB_REGISTRY_IMAGE .
    - docker push "$HUB_REGISTRY_IMAGE"
  only:
    - master
